name: black_jack_21_flutter
description: Blackjack 21 simplified game

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  curl_logger_dio_interceptor: ^1.0.0
  dio_smart_retry: ^5.0.0

  # Firebase
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_performance: ^0.9.2+1
  firebase_performance_dio: ^0.5.0
  firebase_analytics: ^10.4.1
  firebase_remote_config: ^4.2.5

  # State management:
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  get_it: ^7.6.4
  injectable: ^2.3.1
  auto_route: ^7.8.4
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0
  permission_handler: ^11.0.1
  platform: ^3.1.3

  # UI
  lottie: ^2.3.2

  # Data
  copy_with_extension: ^5.0.2
  collection: ^1.17.2
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  image_picker: ^0.8.7+5
  jwt_decoder: ^2.0.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Env
  flutter_flavorizr: ^2.2.1

  # Lint
  flutter_lints: ^2.0.3
  analyzer: ^5.13.0

  # Data
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mobx_codegen: ^2.4.0
  copy_with_extension_gen: ^5.0.4
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.0

  # Tests
  mockito: ^5.4.2
  covadge: ^0.0.1
  permission_handler_platform_interface: ^3.11.5
  plugin_platform_interface: ^2.1.6

  # UI
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  ide: idea
  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    - flutter:flavors
    - flutter:app
    - flutter:targets
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
    - google:firebase
    - assets:clean
    - ide:config

  flavors:
    stg:
      app:
        name: "[Stg]Blackjack 21"
      android:
        applicationId: "com.dvo.blackjack21.stg"
        firebase:
          config: ".firebase/stg/google-services.json"
      ios:
        bundleId: "com.dvo.blackjack21.stg"
        firebase:
          config: ".firebase/stg/GoogleService-Info.plist"
        variables:
          APPLINK_SCHEME:
            value: "dvoblackjack21stg"
    prod:
      app:
        name: "Blackjack 21"
      android:
        applicationId: "com.dvo.blackjack21"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "com.dvo.blackjack21"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"
        variables:
          APPLINK_SCHEME:
            value: "dvoblackjack21"
