// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwlRG7Z6gBC1AxEW08rchCYBD5LPTY9wg',
    appId: '1:1017821902237:web:bb073a4ad341ed16aeeb74',
    messagingSenderId: '1017821902237',
    projectId: 'blackjack21-stg',
    authDomain: 'blackjack21-stg.firebaseapp.com',
    storageBucket: 'blackjack21-stg.appspot.com',
    measurementId: 'G-5VPTX6RY9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrLI7GjkAj5fYEXDqzAkHdYaYMlML_CIg',
    appId: '1:1017821902237:android:e56693f5f0acc030aeeb74',
    messagingSenderId: '1017821902237',
    projectId: 'blackjack21-stg',
    storageBucket: 'blackjack21-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvKl71c7OIRiOjEuRaTDpLSByAUvnpp4',
    appId: '1:1017821902237:ios:6c9087fc850324d5aeeb74',
    messagingSenderId: '1017821902237',
    projectId: 'blackjack21-stg',
    storageBucket: 'blackjack21-stg.appspot.com',
    iosBundleId: 'com.dvo.blackjack21.stg',
  );
}
