// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkPvELp2LDMPOG3TnuTzWQoneKbTrpIv0',
    appId: '1:352061648512:web:c30b3c94299bf3e7fa8065',
    messagingSenderId: '352061648512',
    projectId: 'blackjack21-prod',
    authDomain: 'blackjack21-prod.firebaseapp.com',
    storageBucket: 'blackjack21-prod.appspot.com',
    measurementId: 'G-MLZVRNKYMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDejogd_RmjD9CWo36rjU516ZT1Q0ecRo',
    appId: '1:352061648512:android:e34c42778a71060efa8065',
    messagingSenderId: '352061648512',
    projectId: 'blackjack21-prod',
    storageBucket: 'blackjack21-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5UjI5ruP5WU7pi2Ux6ohSzdXETcvvvV8',
    appId: '1:352061648512:ios:1eb43d2cfd2cc8c2fa8065',
    messagingSenderId: '352061648512',
    projectId: 'blackjack21-prod',
    storageBucket: 'blackjack21-prod.appspot.com',
    iosBundleId: 'com.dvo.blackjack21',
  );
}
